CREATE TABLE CATEGORY(
CATEGORY_NO VARCHAR2(10) PRIMARY KEY,
CATEGORY_NAME VARCHAR2(20) NOT NULL
); 


CREATE TABLE CATEGORY(
	CAR_NO NUMBER NOT NULL,
	CAR_NAME VARCHER2(100) NOT NULL,
	
);

CREATE TABLE CAR_INFO(
	CAR_NO NUMBER NOT NULL,
	CAR_NAME VARCHER2(100) NOT NULL,
	
);


CREATE TABLE RENT_CAR_INFO(
	
);