CREATE TABLE CATEGORY(
CATEGORY_NO VARCHAR2(10) PRIMARY KEY,
CATEGORY_NAME VARCHAR2(20) NOT NULL
); 


CREATE TABLE CATEGORY(
	CAR_NO NUMBER NOT NULL,
	CAR_NAME VARCHAR2(100) NOT NULL,
	
);

CREATE TABLE CAR_INFO(
	CAR_NO NUMBER PRIMARY KEY,
	CAR_NAME VARCHAR2(100) NOT NULL,
	CAR_CATEGORY VARCHAR2(20) NOT NULL,
	CAR_YEAR NUMBER NOT NULL,
	CAR_COMPANY VARCHAR2(20) NOT NULL,
	CAR_BATTERY VARCHAR2(20) NOT NULL,
	ENROLL_DATE DATE NOT NULL	
);


CREATE TABLE RENT_CAR_INFO(
	
);