-- 상품 정보 테이블
CREATE TABLE PRODUCT_INFO (
     PRODUCT_ID       VARCHAR2(30) PRIMARY KEY,  -- 상품코드
     PRODUCT_NAME     VARCHAR2(100),          -- 상품명
     PRODUCT_TYPE    VARCHAR2(50),           -- 옷 종류
     PRODUCT_CATEGORY VARCHAR2(10),              -- '남자', '여자', '아이','신상'
     PRODUCT_PRICE    NUMBER,               -- 가격
     PRODUCT_IMAGE    VARCHAR2(100)          -- 이미지 경로
  
);

-- 요청시 category첫글자 

-- 회원 테이블
CREATE TABLE UNIKLO_MEMBER(
   MEMBER_ID     VARCHAR2(30) PRIMARY KEY,
   MEMBER_PW     VARCHAR2(100) NOT NULL,
   MEMBER_NAME  VARCHAR2(20) NOT NULL,
   MEMBER_PHONE VARCHAR2(20) NOT NULL UNIQUE,
   ROLE VARCHAR2(15) NOT NULL,
   ENROLL_DATE  DATE DEFAULT SYSDATE
  
);

SELECT * FROM UNIKLO_MEMBER;




-- 구매한 상품 테이블
CREATE TABLE PURCHASE_PRODUCT (
   PURCHASE_ID  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
   MEMBER_ID       VARCHAR2(30),
   PRODUCT_ID      VARCHAR2(30),
   PURCHASE_DATE DATE DEFAULT SYSDATE,
   FOREIGN KEY (MEMBER_ID) REFERENCES  UNIKLO_MEMBER(MEMBER_ID),
   FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_INFO(PRODUCT_ID)
);


CREATE TABLE COMMENTS (
  COMMENT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MEMBER_ID     VARCHAR2(30),
  CONTENT       VARCHAR2(1000),
  CREATE_DATE  DATE DEFAULT SYSDATE,
  FOREIGN KEY (MEMBER_ID) REFERENCES UNIKLO_MEMBER(MEMBER_ID)
);



SELECT * FROM UNIKLO_MEMBER;
SELECT * FROM PURCHASE_PRODUCT;
SELECT * FROM COMMENTS;


INSERT INTO PRODUCT_INFO VALUES('MP2323222',
                        'PPPPaRRRRRR',
                        'pants',
                        'men',
                        220000,
                        '/images/men/men-pants5.png'
                        );

SELECT * FROM PRODUCT_INFO;




COMMIT;


DROP TABLE PRODUCT_INFO;




SELECT * FROM PRODUCT_INFO
WHERE PRODUCT_TYPE = 'collection'
AND PRODUCT_CATEGORY = 'new';









